CLASSES = {
    0: 'league',
    1: 'Aatrox',
    2: 'Ability',
    3: 'Ahri',
    4: 'Akali',
    5: 'Akshan',
    6: 'Alistar',
    7: 'Ambessa',
    8: 'Amumu',
    9: 'Anivia',
    10: 'Annie',
    11: 'Aphelios',
    12: 'Ashe',
    13: 'AurelionSol',
    14: 'Aurora',
    15: 'Azir',
    16: 'Bard',
    17: 'Belveth',
    18: 'Blitzcrank',
    19: 'Blue Cannon',
    20: 'Blue Caster',
    21: 'Blue Melee',
    22: 'Blue Siege',
    23: 'BlueInhibitor',
    24: 'BlueNexus',
    25: 'BlueTower',
    26: 'Brand',
    27: 'Braum',
    28: 'Briar',
    29: 'Caitlyn',
    30: 'Camille',
    31: 'Cassiopeia',
    32: 'Chogath',
    33: 'Corki',
    34: 'Darius',
    35: 'Diana',
    36: 'DrMundo',
    37: 'Draven',
    38: 'Ekko',
    39: 'Elise',
    40: 'Evelynn',
    41: 'Ezreal',
    42: 'Fiddlesticks',
    43: 'Fiora',
    44: 'Fizz',
    45: 'Galio',
    46: 'Gangplank',
    47: 'Garen',
    48: 'Gnar',
    49: 'Gragas',
    50: 'Graves',
    51: 'Gwen',
    52: 'Hecarim',
    53: 'Heimerdinger',
    54: 'Hwei',
    55: 'Illaoi',
    56: 'Irelia',
    57: 'Ivern',
    58: 'Janna',
    59: 'JarvanIV',
    60: 'Jax',
    61: 'Jayce',
    62: 'Jhin',
    63: 'Jinx',
    64: 'KSante',
    65: 'Kaisa',
    66: 'Kalista',
    67: 'Karma',
    68: 'Karthus',
    69: 'Kassadin',
    70: 'Katarina',
    71: 'Kayle',
    72: 'Kayn',
    73: 'Kennen',
    74: 'Khazix',
    75: 'Kindred',
    76: 'Kled',
    77: 'KogMaw',
    78: 'Leblanc',
    79: 'LeeSin',
    80: 'Leona',
    81: 'Lillia',
    82: 'Lissandra',
    83: 'Lucian',
    84: 'Lulu',
    85: 'Lux',
    86: 'Malphite',
    87: 'Malzahar',
    88: 'Maokai',
    89: 'MasterYi',
    90: 'Mel',
    91: 'Milio',
    92: 'MissFortune',
    93: 'MonkeyKing',
    94: 'Mordekaiser',
    95: 'Morgana',
    96: 'Naafiri',
    97: 'Nami',
    98: 'Nasus',
    99: 'Nautilus',
    100: 'Neeko',
    101: 'Nidalee',
    102: 'Nilah',
    103: 'Nocturne',
    104: 'Nunu',
    105: 'Olaf',
    106: 'Orianna',
    107: 'Ornn',
    108: 'Pantheon',
    109: 'Pet',
    110: 'Pit',
    111: 'Poppy',
    112: 'Pyke',
    113: 'Qiyana',
    114: 'Quinn',
    115: 'Rakan',
    116: 'Rammus',
    117: 'Red Cannon',
    118: 'Red Caster',
    119: 'Red Melee',
    120: 'RedInhibitor',
    121: 'RedNexus',
    122: 'RedSiege',
    123: 'RedTower',
    124: 'RekSai',
    125: 'Rell',
    126: 'Renata',
    127: 'Renekton',
    128: 'Rengar',
    129: 'Riven',
    130: 'Rumble',
    131: 'Ryze',
    132: 'Samira',
    133: 'Sejuani',
    134: 'Senna',
    135: 'Seraphine',
    136: 'Sett',
    137: 'Shaco',
    138: 'Shen',
    139: 'Shyvana',
    140: 'Singed',
    141: 'Sion',
    142: 'Sivir',
    143: 'Skarner',
    144: 'Smolder',
    145: 'Sona',
    146: 'Soraka',
    147: 'Swain',
    148: 'Sylas',
    149: 'Syndra',
    150: 'TahmKench',
    151: 'Taliyah',
    152: 'Talon',
    153: 'Taric',
    154: 'Teemo',
    155: 'Thresh',
    156: 'Tristana',
    157: 'Trundle',
    158: 'Tryndamere',
    159: 'TwistedFate',
    160: 'Twitch',
    161: 'Udyr',
    162: 'Urgot',
    163: 'Varus',
    164: 'Vayne',
    165: 'Veigar',
    166: 'Vex',
    167: 'Vi',
    168: 'Viego',
    169: 'Viktor',
    170: 'Vladimir',
    171: 'Volibear',
    172: 'Warwick',
    173: 'Xayah',
    174: 'Xerath',
    175: 'XinZhao',
    176: 'Yasuo',
    177: 'Yone',
    178: 'Yorick',
    179: 'Yuumi',
    180: 'Zac',
    181: 'Zed',
    182: 'Zeri',
    183: 'Ziggs',
    184: 'Zilean',
    185: 'Zoe',
    186: 'Zyra', 
    187: 'BlueChampionHealthbar',
    188: 'RedChampionHealthbar',
    189: 'BlueMinionHealthbar',
    190: 'RedMinionHealthbar',
}

TOP_LANERS = ["Aatrox", "Camille", "Darius", "DrMundo", "Garen", "Gragas", "Kennen", "Kled", "Pantheon", "Sett", "Shen", "Sylas", "Volibear", "Yasuo", "Yone"]

TOP_LANER_TO_EMB_I = {
    "Aatrox": 0,
    "Camille": 1,
    "Darius": 2,
    "DrMundo": 3,
    "Garen": 4,
    "Gragas": 5,
    "Kennen": 6,
    "Kled": 7,
    "Pantheon": 8,
    "Sett": 9,
    "Shen": 10,
    "Sylas": 11,
    "Volibear": 12,
    "Yasuo": 13,
    "Yone": 14,
    "Unknown": 15
}

CONDENSED_CHAMPIONS = [
    "Aatrox",
    "Aphelios",
    "Annie",
    "Aurora",
    "Bard",
    "Belveth",
    "Camille",
    "Darius",
    "Diana",
    "DrMundo",
    "Ezreal",
    "Garen",
    "Gragas",
    "Hwei",
    "Ivern",
    "JarvanIV",
    "Karthus",
    "Kennen",
    "Khazix",
    "Kindred",
    "Kled",
    "Lucian",
    "Naafiri",
    "Nami",
    "Neeko",
    "Nunu",
    "Orianna",
    "Pantheon",
    "Rakan",
    "Samira",
    "Senna",
    "Seraphine",
    "Sett",
    "Shaco",
    "Shen",
    "Smolder",
    "Swain",
    "Sylas",
    "Syndra",
    "Talon",
    "Thresh",
    "Veigar",
    "Viktor",
    "Volibear",
    "Xayah",
    "Yasuo",
    "Yone",
    "Yuumi",
    "Ziggs",
    "Zilean",  
    "Red Cannon", 
    "Red Caster",
    "Red Melee",
    "RedSiege", 
    "Blue Cannon",
    "Blue Caster",
    "Blue Melee",
    "BlueSiege",
    "RedTower", 
    "RedInhibitor",
    "RedNexus",
    "BlueTower",
    "BlueInhibitor",
    "BlueNexus",
    "UnknownChampion",
    "UnknownMinion",
    "UnknownTower"
]

CONDENSED_CHAMPIONS_TO_I = {name: i for i, name in enumerate(CONDENSED_CHAMPIONS)}

HEALTHBAR_CLASSES = ["BlueChampionHealthbar", "RedChampionHealthbar", "BlueMinionHealthbar", "RedMinionHealthbar"]
